queue_rules:
  - name: default
    conditions:
      - "check-success=ci/circleci: say-hello"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "check-success=ci/circleci: sleep"
      - -draft
      - label=mergeable
      - -title~=WIP
    actions:
      queue:
        name: default
        method: squash

  - name: Assign reviews to @PawelLipski
    conditions:
      - -closed
      - or:
        - files~=ArchUnitSpec\.scala$
        - files~=^ci/
        - files~=/ConfigsSpec\.scala$
        - files~=^deploy/
        - files~=^dev/
        - files~=^infra/
        - files~=^Jenkinsfile
        - files~=^k8s-operations/
        - files~=\.md$
        - files~=^project/
        - files~=\.sbt$
        - files~=\.sh$
        - files~=/SlickSchemasSpec\.scala$
        - files~=\.yaml$
        - files~=\.yml$
    actions:
      request_reviews:
        users:
          - git-machete-bot
