queue_rules:
  - name: default
    conditions:
      - "check-success=ci/circleci: sleep"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "check-success=ci/circleci: sleep"
      - -draft
      - label=mergeable
      - -title~=WIP
    actions:
      queue:
        name: default
        method: squash

  - name: Assign reviews to @PawelLipski
    conditions:
      - files~=\.yml$
    actions:
      assign:
        add_users:
          - git-machete-bot
          - PawelLipski
      request_reviews:
        users:
          - git-machete-bot
          - PawelLipski
