queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
#      - "check-success=ci/circleci: sleep"
#      - -draft
      - label=mergeable
    actions:
      queue:
        name: default
        method: squash

  - name: Assign reviews to @git-machete-bot
    conditions:
      - files~=\.yml$
    actions:
      assign:
      request_reviews:
        users:
          - git-machete-bot
