# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  sleep:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Sleep"
          command: "sleep 10"

workflows:
  say-hello-workflow:
    jobs:
      - sleep
