# bar
# bar
version: 2.1
jobs:
  sleep:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Sleep"
          command: "sleep 100"
workflows:
  say-hello-workflow:
    jobs:
      - sleep
# fooo
# fooo