version: 2.1
jobs:
  sleep:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: "Sleep"
          command: "sleep 45; exit"
workflows:
  say-hello-workflow:
    jobs:
      - sleep
